# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(400, 0, 20, 561))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 462, 71, 71))
        self.pushButton.setStyleSheet("border-radius: 35px;\n"
"background-color: white;\n"
"font-size: 50px;\n"
"padding-bottom: 5px;\n"
"background-color: #081540;\n"
"color: white;\n"
"")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 37))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.todayButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.todayButton.setMinimumSize(QtCore.QSize(0, 35))
        self.todayButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 25px;\n"
"border-bottom: 1px solid purple;")
        self.todayButton.setObjectName("todayButton")
        self.horizontalLayout.addWidget(self.todayButton)
        self.weeklyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.weeklyButton.setEnabled(True)
        self.weeklyButton.setMinimumSize(QtCore.QSize(0, 35))
        self.weeklyButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 25px;")
        self.weeklyButton.setObjectName("weeklyButton")
        self.horizontalLayout.addWidget(self.weeklyButton)
        self.overviewButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.overviewButton.setMinimumSize(QtCore.QSize(0, 35))
        self.overviewButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 25px;")
        self.overviewButton.setObjectName("overviewButton")
        self.horizontalLayout.addWidget(self.overviewButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Goals"))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.todayButton.setText(_translate("MainWindow", "Today"))
        self.weeklyButton.setText(_translate("MainWindow", "Weekly"))
        self.overviewButton.setText(_translate("MainWindow", "Overview"))
