# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 701)
        MainWindow.setStyleSheet("background-color: #F6F5F9; font-size: 20px;")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 0, 20, 711))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.newGoal = QtWidgets.QPushButton(self.centralwidget)
        self.newGoal.setGeometry(QtCore.QRect(430, 630, 50, 50))
        self.newGoal.setStyleSheet("border-radius:25px;\n"
"background-color: white;\n"
"font-size: 35px;\n"
"padding-bottom: 5px;\n"
"background-color: #081540;\n"
"color: white;\n"
"")
        self.newGoal.setIconSize(QtCore.QSize(16, 16))
        self.newGoal.setObjectName("newGoal")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.expandLeft = QtWidgets.QHBoxLayout()
        self.expandLeft.setSpacing(0)
        self.expandLeft.setObjectName("expandLeft")
        self.overviewButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.overviewButton.setMinimumSize(QtCore.QSize(0, 35))
        self.overviewButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 10px;")
        self.overviewButton.setObjectName("overviewButton")
        self.expandLeft.addWidget(self.overviewButton)
        self.todayButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.todayButton.setMinimumSize(QtCore.QSize(0, 35))
        self.todayButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 10px;\n"
"border-bottom: 1px solid purple;")
        self.todayButton.setObjectName("todayButton")
        self.expandLeft.addWidget(self.todayButton)
        self.weeklyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.weeklyButton.setEnabled(True)
        self.weeklyButton.setMinimumSize(QtCore.QSize(0, 35))
        self.weeklyButton.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding: 10px;")
        self.weeklyButton.setObjectName("weeklyButton")
        self.expandLeft.addWidget(self.weeklyButton)
        self.expandLeft.setStretch(0, 1)
        self.expandLeft.setStretch(1, 1)
        self.expandLeft.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.expandLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 451, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.goals = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.goals.setContentsMargins(25, 0, 0, 0)
        self.goals.setSpacing(25)
        self.goals.setObjectName("goals")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(540, 80, 431, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.goalDescription = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.goalDescription.setContentsMargins(0, 0, 0, 0)
        self.goalDescription.setObjectName("goalDescription")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 427, 127))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.goalDescription.addWidget(self.scrollArea)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(540, 220, 431, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.subgoals = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.subgoals.setContentsMargins(0, 0, 0, 0)
        self.subgoals.setSpacing(25)
        self.subgoals.setObjectName("subgoals")
        self.newSubgoal = QtWidgets.QPushButton(self.centralwidget)
        self.newSubgoal.setGeometry(QtCore.QRect(930, 480, 25, 25))
        self.newSubgoal.setStyleSheet("border-radius:25px;\n"
"background-color: white;\n"
"font-size: 35px;\n"
"padding-bottom: 5px;\n"
"background-color: #081540;\n"
"color: white;\n"
"")
        self.newSubgoal.setIconSize(QtCore.QSize(16, 16))
        self.newSubgoal.setObjectName("newSubgoal")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Goals"))
        self.newGoal.setText(_translate("MainWindow", "+"))
        self.overviewButton.setText(_translate("MainWindow", "Overview"))
        self.todayButton.setText(_translate("MainWindow", "Today"))
        self.weeklyButton.setText(_translate("MainWindow", "Weekly"))
        self.newSubgoal.setText(_translate("MainWindow", "+"))
