name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: simple-goals

    - uses: actions/upload-artifact@v2
      with:
        name: simple-goals
        path: src/dist/simple-goals # or path/to/artifact
